# TCL File Generated by Component Editor 12.1sp1
# Mon Feb 08 10:22:59 MST 2016
# DO NOT MODIFY


# 
# YCrCb_to_RGB "YCrCb_to_RGB" v1.0
# null 2016.02.08.10:22:59
# 
# 

# 
# request TCL package from ACDS 12.1
# 
package require -exact qsys 12.1


# 
# module YCrCb_to_RGB
# 
set_module_property NAME YCrCb_to_RGB
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME YCrCb_to_RGB
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL YCrCb_to_RGB
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file YCrCb_444_to_24_RGB.vhd VHDL PATH ../vhdl/YCrCb_444_to_24_RGB.vhd
add_fileset_file YCrCb_to_RGB_converter.vhd VHDL PATH ../vhdl/YCrCb_to_RGB_converter.vhd

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL YCrCb_to_RGB
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file YCrCb_444_to_24_RGB.vhd VHDL PATH ../vhdl/YCrCb_444_to_24_RGB.vhd
add_fileset_file YCrCb_to_RGB_converter.vhd VHDL PATH ../vhdl/YCrCb_to_RGB_converter.vhd


# 
# parameters
# 
add_parameter IW INTEGER 23
set_parameter_property IW DEFAULT_VALUE 23
set_parameter_property IW DISPLAY_NAME IW
set_parameter_property IW TYPE INTEGER
set_parameter_property IW UNITS None
set_parameter_property IW ALLOWED_RANGES -2147483648:2147483647
set_parameter_property IW HDL_PARAMETER true
add_parameter OW INTEGER 23
set_parameter_property OW DEFAULT_VALUE 23
set_parameter_property OW DISPLAY_NAME OW
set_parameter_property OW TYPE INTEGER
set_parameter_property OW UNITS None
set_parameter_property OW ALLOWED_RANGES -2147483648:2147483647
set_parameter_property OW HDL_PARAMETER true
add_parameter EIW INTEGER 1
set_parameter_property EIW DEFAULT_VALUE 1
set_parameter_property EIW DISPLAY_NAME EIW
set_parameter_property EIW TYPE INTEGER
set_parameter_property EIW UNITS None
set_parameter_property EIW ALLOWED_RANGES -2147483648:2147483647
set_parameter_property EIW HDL_PARAMETER true
add_parameter EOW INTEGER 1
set_parameter_property EOW DEFAULT_VALUE 1
set_parameter_property EOW DISPLAY_NAME EOW
set_parameter_property EOW TYPE INTEGER
set_parameter_property EOW UNITS None
set_parameter_property EOW ALLOWED_RANGES -2147483648:2147483647
set_parameter_property EOW HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true

add_interface_port reset reset reset Input 1


# 
# connection point avalon_streaming_source
# 
add_interface avalon_streaming_source avalon_streaming start
set_interface_property avalon_streaming_source associatedClock clock
set_interface_property avalon_streaming_source associatedReset reset
set_interface_property avalon_streaming_source dataBitsPerSymbol 8
set_interface_property avalon_streaming_source errorDescriptor ""
set_interface_property avalon_streaming_source firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_source maxChannel 0
set_interface_property avalon_streaming_source readyLatency 0
set_interface_property avalon_streaming_source ENABLED true

add_interface_port avalon_streaming_source stream_out_ready ready Input 1
add_interface_port avalon_streaming_source stream_out_startofpacket startofpacket Output 1
add_interface_port avalon_streaming_source stream_out_endofpacket endofpacket Output 1
add_interface_port avalon_streaming_source stream_out_data data Output "(ow) - (0) + 1"
add_interface_port avalon_streaming_source stream_out_valid valid Output 1


# 
# connection point avalon_streaming_sink
# 
add_interface avalon_streaming_sink avalon_streaming end
set_interface_property avalon_streaming_sink associatedClock clock
set_interface_property avalon_streaming_sink associatedReset reset
set_interface_property avalon_streaming_sink dataBitsPerSymbol 8
set_interface_property avalon_streaming_sink errorDescriptor ""
set_interface_property avalon_streaming_sink firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_sink maxChannel 0
set_interface_property avalon_streaming_sink readyLatency 0
set_interface_property avalon_streaming_sink ENABLED true

add_interface_port avalon_streaming_sink stream_in_data data Input "(iw) - (0) + 1"
add_interface_port avalon_streaming_sink stream_in_startofpacket startofpacket Input 1
add_interface_port avalon_streaming_sink stream_in_endofpacket endofpacket Input 1
add_interface_port avalon_streaming_sink stream_in_ready ready Output 1
add_interface_port avalon_streaming_sink stream_in_valid valid Input 1

